const data = {
    products:[
        {
            _id:'1',
            name:'Converse Shoes',
            category:'Shoes',
            image:'/images/product-1.png',
            price: 120,
            brand: 'Converse',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Nike Shirt',
            category:'Shirt',
            image:'/images/product-1.png',
            price: 54,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Adidas sport shorts',
            category:'Shorts',
            image:'/images/product-1.png',
            price: 89,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Converse Hat',
            category:'Hat',
            image:'/images/product-1.png',
            price: 30,
            brand: 'Converse',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Converse Socks',
            category:'Socks',
            image:'/images/product-1.png',
            price: 25,
            brand: 'Converse',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Lacoste Belt',
            category:'Belt',
            image:'/images/product-1.png',
            price: 45,
            brand: 'Lacoste',
            rating: 5.0,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;